export const NavigationData = {
  categories: [
    {
      id: "product",
      name: "Product",
      sections: [
        {
          id: "bulb",
          name: "Bulb",
          items: [
            { name: "9 Watt LED Bulb", _id: "676" },
            { name: "12 Watt LED Bulb", _id: "677" },
            { name: "15 Watt LED Bulb", _id: "678" },
            { name: "Smart LED Bulb", _id: "679" },
            { name: "Emergency LED Bulb", _id: "680" },
          ],
        },
        {
          id: "fan",
          name: "Fan",
          items: [
            { name: "Ceiling Fan", _id: "681" },
            { name: "Table Fan", _id: "682" },
            { name: "Wall Fan", _id: "683" },
            { name: "Exhaust Fan", _id: "684" },
            { name: "Pedestal Fan", _id: "685" },
          ],
        },
        {
          id: "wire",
          name: "Wire",
          items: [
            { name: "Copper Wire (1.5mm)", _id: "686" },
            { name: "Copper Wire (2.5mm)", _id: "687" },
            { name: "Aluminum Wire (1.5mm)", _id: "688" },
            { name: "Aluminum Wire (2.5mm)", _id: "689" },
            { name: "Flexible Wire", _id: "690" },
          ],
        },
        {
          id: "fuse",
          name: "Fuse",
          items: [
            { name: "5 Amp Fuse", _id: "691" },
            { name: "10 Amp Fuse", _id: "692" },
            { name: "15 Amp Fuse", _id: "693" },
            { name: "20 Amp Fuse", _id: "694" },
            { name: "25 Amp Fuse", _id: "695" },
          ],
        },
        {
          id: "wiring_pipe",
          name: "Wiring Pipe",
          items: [
            { name: "PVC Pipe (1/2 inch)", _id: "696" },
            { name: "PVC Pipe (3/4 inch)", _id: "697" },
            { name: "Conduit Pipe (1/2 inch)", _id: "698" },
            { name: "Conduit Pipe (3/4 inch)", _id: "699" },
            { name: "Flexible Pipe", _id: "700" },
          ],
        },
        {
          id: "switch",
          name: "Switch",
          items: [
            { name: "Single Pole Switch", _id: "701" },
            { name: "Double Pole Switch", _id: "702" },
            { name: "Three-Way Switch", _id: "703" },
            { name: "Four-Way Switch", _id: "704" },
            { name: "Dimmer Switch", _id: "705" },
          ],
        },
        {
          id: "socket",
          name: "Socket",
          items: [
            { name: "2-Pin Socket", _id: "706" },
            { name: "3-Pin Socket", _id: "707" },
            { name: "Universal Socket", _id: "708" },
            { name: "Industrial Socket", _id: "709" },
            { name: "USB Socket", _id: "710" },
          ],
        },
      ],
    },
    {
      id: "brands",
      name: "Brands",
      sections: [
        {
          id: "brands",
          name: "Brands",
          items: [
            { name: "Philips", _id: "801" },
            { name: "Syska", _id: "802" },
            { name: "Havells", _id: "803" },
            { name: "Wipro", _id: "804" },
            { name: "Bajaj", _id: "805" },
            { name: "Orient", _id: "806" },
            { name: "Usha", _id: "807" },
            { name: "Crompton", _id: "808" },
            { name: "Finolex", _id: "809" },
            { name: "RR Kabel", _id: "810" },
            { name: "Polycab", _id: "811" },
            { name: "KEI", _id: "812" },
            { name: "L&T", _id: "813" },
            { name: "Siemens", _id: "814" },
            { name: "ABB", _id: "815" },
            { name: "Schneider", _id: "816" },
            { name: "Astral", _id: "817" },
            { name: "Supreme", _id: "818" },
            { name: "Prince", _id: "819" },
            { name: "Legrand", _id: "820" },
            { name: "Anchor", _id: "821" },
          ],
        },
      ],
    },
  ],
};
